image: quay.io/openshift-pipeline/openshift-cli:latest

stages:
  - build
  - deploy

variables:
  OPENSHIFT_PROJECT: sample-tracing

before_script:
  - oc login $OPENSHIFT_ADDRESS --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
  - oc project $OPENSHIFT_PROJECT

production_build:
  stage: build
  only:
    - master
  script: |
    ./build.sh

production_deploy:
  stage: deploy
  only:
    - master
  script: |
    ./deploy.sh
