apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: sample-gateway
  labels:
    app: sample-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: sample-gateway
    deploymentconfig: sample-gateway
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: sample-gateway
        version: v1
        deploymentconfig: sample-gateway
    spec:
      restartPolicy: Always
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        name: sample-gateway
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: sample-gateway-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: sample-gateway
  labels:
    app: sample-gateway
    service: sample-gateway
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: sample-gateway
    deploymentconfig: sample-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-gateway-cfg
data:
  SERVICE_NAME: "sample-gateway"
  SERVICE_NUM: "3"
  PROPAGATE1: "http://dest1:8080"
  PROPAGATE2: "http://dest1:8080/propagate2"
  PROPAGATE3: "http://dest3:8080"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-gateway
  namespace: sample-tracing
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-gateway
  namespace: sample-tracing
spec:
  hosts:
  - "*"
  gateways:
  - sample-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /propagate1
    - uri:
        exact: /propagate2
    - uri:
        exact: /propagate3
    route:
    - destination:
        host: sample-gateway
        port:
          number: 8080
  - match:
    - uri:
        exact: /eventlistener
    route:
    - destination:
        host: el-pipeline-listener
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sample-gateway
  namespace: sample-tracing
spec:
  host: sample-gateway
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: el-pipeline-listener
spec:
  host: el-pipeline-listener
  subsets:
  - name: v1
    labels:
      version: v1
