apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dest1-v1
  labels:
    app: dest1
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest1
        version: v1
    spec:
      containers:
      - name: dest1
        image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest1-v1-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: dest1
  labels:
    app: dest1
    service: dest1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dest1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest1-v1-cfg
data:
  SERVICE_NAME: "dest1-v1"
  SERVICE_NUM: "3"
  PROPAGATE2: "http://dest2:8080"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dest1
spec:
  hosts:
  - dest1
  http:
  - route:
    - destination:
        host: dest1
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dest1
spec:
  host: dest1
  subsets:
  - name: v1
    labels:
      version: v1
