apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dest1-v2
  labels:
    app: dest1
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest1
        version: v2
    spec:
      containers:
      - name: dest1
        image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest1-v2-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest1-v2-cfg
data:
  SERVICE_NAME: "dest1-v2"
  SERVICE_NUM: "3"
  PROPAGATE2: "http://dest2:8080"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dest1
spec:
  hosts:
  - dest1
  http:
  - route:
    - destination:
        host: dest1
        subset: v1
      weight: 70
    - destination:
        host: dest1
        subset: v2
      weight: 30
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dest1
spec:
  host: dest1
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
