apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tracing-pipeline
spec:
  resources:
  - name: app-source
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: build-and-push
    params:
    - name: TLSVERIFY
      value: "false"
    resources:
      inputs:
      - name: source
        resource: app-source
      outputs:
      - name: image
        resource: app-image
  - name: deploy-gateway
    taskRef:
      name: oc
    runAfter:
      - build
    params:
    - name: ARGS
      value:
        - "rollout"
        - "latest"
        - "gateway"
  - name: deploy-dest1
    taskRef:
      name: oc
    runAfter:
      - build
    params:
    - name: ARGS
      value:
        - "rollout"
        - "latest"
        - "dest1"
  - name: deploy-dest2
    taskRef:
      name: oc
    runAfter:
      - build
    params:
    - name: ARGS
      value:
        - "rollout"
        - "latest"
        - "dest2"
  - name: deploy-dest3
    taskRef:
      name: oc
    runAfter:
      - build
    params:
    - name: ARGS
      value:
        - "rollout"
        - "latest"
        - "dest3"
