apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: tracing-task-run
spec:
  taskRef:
    name: build-and-push
  serviceAccount: 'pipeline'
  inputs:
    resources:
    - name: source
      resourceRef:
        name: pipeline-source
  outputs:
    resources:
    - name: image
      resourceRef:
        name: pipeline-image
