apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dest2-v1
  labels:
    app: dest2
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest2
        version: v1
    spec:
      containers:
      - name: dest2
        image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest2-v1-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: dest2
  labels:
    app: dest2
    service: dest2
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dest2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest2-v1-cfg
data:
  SERVICE_NAME: "dest2-v1"
  SERVICE_NUM: "3"
