apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dest2
  name: dest2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: dest2
    deploymentconfig: dest2
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest2
        version: v1
        deploymentconfig: dest2
    spec:
      restartPolicy: Always
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        name: dest2
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest2-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: dest2
  labels:
    app: dest2
    service: dest2
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dest2
    deploymentconfig: dest2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest2-cfg
data:
  SERVICE_NAME: "dest2"
  SERVICE_NUM: "3"
