apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dest2
  name: dest2
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    app: dest2
    deploymentconfig: dest2
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest2
        version: v1
        deploymentconfig: dest2
    spec:
      restartPolicy: Always
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/sample-tracing/dest2:latest
        imagePullPolicy: Always
        name: dest2
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dest2-svc
  labels:
    app: dest2-svc
    service: dest2-svc
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dest2
    deploymentconfig: dest2
