apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dest3
  name: dest3
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: dest3
    deploymentconfig: dest3
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest3
        version: v1
        deploymentconfig: dest3
    spec:
      restartPolicy: Always
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        name: dest3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest3-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: dest3
  labels:
    app: dest3
    service: dest3
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dest3
    deploymentconfig: dest3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest3-cfg
data:
  SERVICE_NAME: "dest3"
  SERVICE_NUM: "3"
