apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dest3
spec:
  hosts:
  - dest3
  http:
  - route:
    - destination:
        host: dest3
        subset: v1
    fault:
      abort:
        httpStatus: 503
        percent: 70
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dest3
spec:
  host: dest3
  subsets:
  - name: v1
    labels:
      version: v1
