apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dest3-v1
  labels:
    app: dest3
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dest3
        version: v1
    spec:
      containers:
      - name: dest3
        image: image-registry.openshift-image-registry.svc:5000/sample-tracing/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dest3-v1-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: dest3
  labels:
    app: dest3
    service: dest3
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dest3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dest3-v1-cfg
data:
  SERVICE_NAME: "dest3-v1"
  SERVICE_NUM: "3"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dest3
spec:
  hosts:
  - dest3
  http:
  - route:
    - destination:
        host: dest3
        subset: v1
    fault:
      abort:
        httpStatus: 503
        percent: 70
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dest3
spec:
  host: dest3
  subsets:
  - name: v1
    labels:
      version: v1
